version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "${PORT}:${PORT}"   
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV} 
    command: npm run start:dev

  db:
    image: postgres:16
    container_name: nest-db
    ports:
      - "${POSTGRES_PORT}:${DB_PORT}" 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-test
    environment:
      NODE_ENV: test
    command: npm run test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
